INSERT INTO burgers (name) VALUES ('Testing, 1, 2, Cheese');
INSERT INTO burgers (name) VALUES ('New Bacon-ings');
INSERT INTO burgers (name) VALUES ('If Looks Could Kale');
INSERT INTO burgers (name) VALUES ('The Say Cheese');
INSERT INTO burgers (name) VALUES ('Thank God its Fried Egg');
INSERT INTO burgers (name) VALUES ('Rest In Peas');
INSERT INTO burgers (name) VALUES ('Fig-eta Bout it');
INSERT INTO burgers (name) VALUES ('Summer Thyme');
INSERT INTO burgers (name) VALUES ('Beets Me');
INSERT INTO burgers (name) VALUES ('Sweet Chili O Mine');